// Copyright 2026 Future Gadget Laboratories.
//
// Licensed under the Apache License, Version 2.0. See licenses/APL.txt.

package main

import (
	"context"
	"fmt"
	"strings"
)

// identityInfo is one GENERATED AS IDENTITY column and the sequence that
// backs it. That sequence is created again by CREATE TABLE, so the backup
// must not also emit CREATE SEQUENCE for it.
type identityInfo struct {
	Column   string
	Sequence string
	Always   bool
}

func readIdentity(ctx context.Context, db *database, database, asOf string) ([]identityInfo, error) {
	var out []identityInfo
	err := db.withSnapshot(ctx, asOf, func(ctx context.Context) error {
		if err := db.use(ctx, database); err != nil {
			return err
		}
		rows, err := db.query(ctx, `
SELECT n.nspname, c.relname, a.attname, a.attidentity::STRING
FROM pg_attribute a
JOIN pg_class c ON c.oid = a.attrelid
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE a.attnum > 0 AND NOT a.attisdropped AND a.attidentity::STRING IN ('a', 'd')
  -- The primary-key index repeats attidentity. pg_get_serial_sequence only
  -- accepts the table, and on 23.2 it errors if handed the index name.
  AND c.relkind = 'r'
  AND n.nspname NOT IN ('pg_catalog', 'information_schema', 'crdb_internal', 'pg_extension')`)
		if err != nil {
			return err
		}
		defer rows.Close()
		type col struct {
			schema, table, name, kind string
		}
		var cols []col
		for rows.Next() {
			var c col
			if err := rows.Scan(&c.schema, &c.table, &c.name, &c.kind); err != nil {
				return err
			}
			cols = append(cols, c)
		}
		if err := rows.Err(); err != nil {
			return err
		}
		for _, c := range cols {
			seq, err := serialSequence(ctx, db, c.schema, c.table, c.name)
			if err != nil {
				return err
			}
			out = append(out, identityInfo{
				Column:   database + "." + c.schema + "." + c.table + "." + c.name,
				Sequence: seq,
				Always:   c.kind == "a",
			})
		}
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("read identity columns in %s: %w", database, err)
	}
	return out, nil
}

func serialSequence(ctx context.Context, db *database, schema, table, column string) (string, error) {
	rel := quoteLiteral(schema + "." + table)
	var seq *string
	err := db.queryRow(ctx, "SELECT pg_get_serial_sequence("+rel+", "+quoteLiteral(column)+")").Scan(&seq)
	if err != nil {
		return "", err
	}
	if seq == nil {
		return "", nil
	}
	return *seq, nil
}

func rejectAlwaysIdentity(infos []identityInfo) error {
	var names []string
	for _, info := range infos {
		if info.Always {
			names = append(names, info.Column)
		}
	}
	if len(names) == 0 {
		return nil
	}
	return fmt.Errorf("cannot back up GENERATED ALWAYS AS IDENTITY columns (%s). CockroachDB rejects COPY and IMPORT into those columns, so the values would be lost. Change them to GENERATED BY DEFAULT AS IDENTITY, or remove them, and take another backup", strings.Join(names, ", "))
}

func ownedSequences(infos []identityInfo) map[string]bool {
	out := map[string]bool{}
	for _, info := range infos {
		if info.Sequence == "" {
			continue
		}
		out[normalizeObjectName(info.Sequence)] = true
	}
	return out
}

func omitOwnedSequences(objects *ObjectsFile, database string, owned map[string]bool) {
	if len(owned) == 0 {
		return
	}
	var kept []Statement
	for _, st := range objects.Statements {
		if st.Database == database && st.Kind == "sequence" && sequenceIsOwned(st.Object, owned) {
			continue
		}
		kept = append(kept, st)
	}
	objects.Statements = kept
}

func sequenceIsOwned(object string, owned map[string]bool) bool {
	name := normalizeObjectName(object)
	if owned[name] {
		return true
	}
	for seq := range owned {
		if sameRoutineName(name, seq) {
			return true
		}
	}
	return false
}
